import {
  AFTER_ERROR_LOAD_INTERVAL,
  INIT_DATA_RELOAD_INTERVAL,
  LEADERS_CURRENT_DATA_RELOAD_COUNT,
  LEADERS_DATA_LOAD_DELAY,
  LEADERS_DATA_RELOAD_INTERVAL,
  LEADERS_OLD_DATA_RELOAD_COUNT,
  TIMER_INTERVAL,
  KUB_CHECK_STATE_INTERVAL,
  ANSWERS_RETRIES
} from "./intervals";
import { HOME_PAGE, LEADERBOARD_PAGE, QUIZ_PAGE, KUB_PAGE } from "./pages";
import { DEFAULT_COUNTRY } from "./phone";
import { LS_USER_KEY, LS_RESULT_KEY } from "./ls";
import { INIT_DEPENDENCY } from "./dependencies";

export {
  AFTER_ERROR_LOAD_INTERVAL,
  ANSWERS_RETRIES,
  DEFAULT_COUNTRY,
  HOME_PAGE,
  INIT_DATA_RELOAD_INTERVAL,
  INIT_DEPENDENCY,
  KUB_CHECK_STATE_INTERVAL,
  KUB_PAGE,
  LEADERBOARD_PAGE,
  LEADERS_CURRENT_DATA_RELOAD_COUNT,
  LEADERS_DATA_LOAD_DELAY,
  LEADERS_DATA_RELOAD_INTERVAL,
  LEADERS_OLD_DATA_RELOAD_COUNT,
  LS_RESULT_KEY,
  LS_USER_KEY,
  QUIZ_PAGE,
  TIMER_INTERVAL
};
